version: '3.4'

services:
  rust:
    container_name: rust
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /usr/src
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/src
